Fix appveyor build
- A treeshaking test was using a symlink file (css.js) which does
  not work correctly when tests are running on windows. This change
  replaces the link with the actual file.

- Upgrade testee to latest version

- Remove wilcards from jshint script
  The script does not work in Windows when wildcards are used:
  ERROR: Can't open lib/**/*.js (seen on appveyor build)

  jshint recursively lints all files when a driectory is passed to
  the CLI so we can pass "lib/" instead of "lib/**/*.js".

- Use latest 8.x version available